pipeline {
    agent any
    stages {
      stage('Init') {
        steps {
          echo 'hello'
        }
      }
      stage('For PR') {
        when {
            branch 'PR-*'
        }
        steps {
          echo "Thos runs on PRs"
        }
      }
  }
}